BEGIN;

DROP TABLE IF EXISTS "person", "thematic","sub_category","media","media_type","gender","relation_ship","contain" ,"family";

CREATE TABLE "thematic"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL, 
    "created_at" TIMESTAMPTZ DEFAULT now(),
    "update_at" TIMESTAMPTZ
);

CREATE TABLE "sub_category"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "category" TEXT NOT NULL,  
    "thematic_id" INT NOT NULL,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    "update_at" TIMESTAMPTZ
);

CREATE TABLE "media"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "url" TEXT NOT NULL UNIQUE,
    "comment" TEXT,      
    "media_type_id" INT NOT NULL,
    "thematic_id" INT, 
    "created_at" TIMESTAMPTZ DEFAULT now(),
    "update_at" TIMESTAMPTZ
);

CREATE TABLE "media_type"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "type" TEXT NOT NULL
);

CREATE TABLE "person"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" TEXT UNIQUE NOT NULL,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "password" TEXT NOT NULL,  
    "family_id" INT NOT NULL ,
    "gender_id" INT NOT NULL,
    "relation_ship_id" INT NOT NULL,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    "update_at" TIMESTAMPTZ
);

CREATE TABLE "gender"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sex" TEXT NOT NULL UNIQUE
);          

CREATE TABLE "relation_ship" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "relation" TEXT NOT NULL UNIQUE
);

CREATE TABLE "family" (
    "id"  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,    
    "media_id" INT,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    "update_at" TIMESTAMPTZ
);

CREATE TABLE "contain"(
    "media_id" INT NOT NULL REFERENCES "media" ("id"),
    "person_id" INT NOT NULL REFERENCES "person" ("id")
);

ALTER TABLE "sub_category" 
    ADD FOREIGN KEY ("thematic_id") REFERENCES "media" ("id");

ALTER TABLE "media"
    ADD FOREIGN KEY ("media_type_id") REFERENCES "media_type" ("id"),
    ADD FOREIGN KEY ("thematic_id") REFERENCES "thematic" ("id");

ALTER TABLE "person"
    ADD FOREIGN KEY("family_id") REFERENCES "family" ("id"),
    ADD FOREIGN KEY("gender_id") REFERENCES "gender" ("id"),
    ADD FOREIGN KEY("relation_ship_id") REFERENCES "relation_ship" ("id");
    
ALTER TABLE "family"
    ADD FOREIGN KEY ("media_id") REFERENCES "media" ("id");
COMMIT;